// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Data/Fitness/FitnessRecord.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct POGOProtos_Data_Fitness_FitnessRecord {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var rawSamples: [POGOProtos_Data_Fitness_FitnessSample] {
    get {return _storage._rawSamples}
    set {_uniqueStorage()._rawSamples = newValue}
  }

  public var lastAggregationTimestampMs: Int64 {
    get {return _storage._lastAggregationTimestampMs}
    set {_uniqueStorage()._lastAggregationTimestampMs = newValue}
  }

  public var fitnessStats: POGOProtos_Data_Fitness_FitnessStats {
    get {return _storage._fitnessStats ?? POGOProtos_Data_Fitness_FitnessStats()}
    set {_uniqueStorage()._fitnessStats = newValue}
  }
  /// Returns true if `fitnessStats` has been explicitly set.
  public var hasFitnessStats: Bool {return _storage._fitnessStats != nil}
  /// Clears the value of `fitnessStats`. Subsequent reads from it will return its default value.
  public mutating func clearFitnessStats() {_uniqueStorage()._fitnessStats = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "POGOProtos.Data.Fitness"

extension POGOProtos_Data_Fitness_FitnessRecord: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FitnessRecord"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    2: .standard(proto: "raw_samples"),
    3: .standard(proto: "last_aggregation_timestamp_ms"),
    4: .standard(proto: "fitness_stats"),
  ]

  fileprivate class _StorageClass {
    var _rawSamples: [POGOProtos_Data_Fitness_FitnessSample] = []
    var _lastAggregationTimestampMs: Int64 = 0
    var _fitnessStats: POGOProtos_Data_Fitness_FitnessStats? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _rawSamples = source._rawSamples
      _lastAggregationTimestampMs = source._lastAggregationTimestampMs
      _fitnessStats = source._fitnessStats
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 2: try decoder.decodeRepeatedMessageField(value: &_storage._rawSamples)
        case 3: try decoder.decodeSingularInt64Field(value: &_storage._lastAggregationTimestampMs)
        case 4: try decoder.decodeSingularMessageField(value: &_storage._fitnessStats)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._rawSamples.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._rawSamples, fieldNumber: 2)
      }
      if _storage._lastAggregationTimestampMs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._lastAggregationTimestampMs, fieldNumber: 3)
      }
      if let v = _storage._fitnessStats {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: POGOProtos_Data_Fitness_FitnessRecord, rhs: POGOProtos_Data_Fitness_FitnessRecord) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._rawSamples != rhs_storage._rawSamples {return false}
        if _storage._lastAggregationTimestampMs != rhs_storage._lastAggregationTimestampMs {return false}
        if _storage._fitnessStats != rhs_storage._fitnessStats {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
