// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Data/Telemetry/PokemonHomeTelemetry.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct POGOProtos_Data_Telemetry_PokemonHomeTelemetry {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var pokemonHomeClickIds: POGOProtos_Data_Telemetry_PokemonHomeTelemetry.PokemonHomeTelemetryIds = .undefinedPokemonHomeEvent

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum PokemonHomeTelemetryIds: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case undefinedPokemonHomeEvent // = 0
    case openSettings // = 1
    case signIn // = 2
    case selectedPokemon // = 3
    case UNRECOGNIZED(Int)

    public init() {
      self = .undefinedPokemonHomeEvent
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .undefinedPokemonHomeEvent
      case 1: self = .openSettings
      case 2: self = .signIn
      case 3: self = .selectedPokemon
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .undefinedPokemonHomeEvent: return 0
      case .openSettings: return 1
      case .signIn: return 2
      case .selectedPokemon: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  public init() {}
}

#if swift(>=4.2)

extension POGOProtos_Data_Telemetry_PokemonHomeTelemetry.PokemonHomeTelemetryIds: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [POGOProtos_Data_Telemetry_PokemonHomeTelemetry.PokemonHomeTelemetryIds] = [
    .undefinedPokemonHomeEvent,
    .openSettings,
    .signIn,
    .selectedPokemon,
  ]
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "POGOProtos.Data.Telemetry"

extension POGOProtos_Data_Telemetry_PokemonHomeTelemetry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PokemonHomeTelemetry"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "pokemon_home_click_ids"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularEnumField(value: &self.pokemonHomeClickIds)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.pokemonHomeClickIds != .undefinedPokemonHomeEvent {
      try visitor.visitSingularEnumField(value: self.pokemonHomeClickIds, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: POGOProtos_Data_Telemetry_PokemonHomeTelemetry, rhs: POGOProtos_Data_Telemetry_PokemonHomeTelemetry) -> Bool {
    if lhs.pokemonHomeClickIds != rhs.pokemonHomeClickIds {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension POGOProtos_Data_Telemetry_PokemonHomeTelemetry.PokemonHomeTelemetryIds: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNDEFINED_POKEMON_HOME_EVENT"),
    1: .same(proto: "OPEN_SETTINGS"),
    2: .same(proto: "SIGN_IN"),
    3: .same(proto: "SELECTED_POKEMON"),
  ]
}
