// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Networking/Requests/Game/GameTelemetry/GameTelemetryAction.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum POGOProtos_Networking_Requests_Game_GameTelemetry_GameTelemetryAction: SwiftProtobuf.Enum {
  public typealias RawValue = Int

  /// No implementation required
  case unknownGameTelemetryAction // = 0

  /// ???
  case collectClientTelemetry // = 610000

  /// Implemented
  case getClientTelemetrySettings // = 610001
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknownGameTelemetryAction
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknownGameTelemetryAction
    case 610000: self = .collectClientTelemetry
    case 610001: self = .getClientTelemetrySettings
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknownGameTelemetryAction: return 0
    case .collectClientTelemetry: return 610000
    case .getClientTelemetrySettings: return 610001
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension POGOProtos_Networking_Requests_Game_GameTelemetry_GameTelemetryAction: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [POGOProtos_Networking_Requests_Game_GameTelemetry_GameTelemetryAction] = [
    .unknownGameTelemetryAction,
    .collectClientTelemetry,
    .getClientTelemetrySettings,
  ]
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension POGOProtos_Networking_Requests_Game_GameTelemetry_GameTelemetryAction: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNKNOWN_GAME_TELEMETRY_ACTION"),
    610000: .same(proto: "COLLECT_CLIENT_TELEMETRY"),
    610001: .same(proto: "GET_CLIENT_TELEMETRY_SETTINGS"),
  ]
}
