// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Settings/Master/CombatNpcPersonality.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct POGOProtos_Settings_Master_CombatNpcPersonality {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var personalityName: String = String()

  public var superEffectiveChance: Float = 0

  public var specialChance: Float = 0

  public var defensiveMinimumScore: Float = 0

  public var defensiveMaximumScore: Float = 0

  public var offensiveMinimumScore: Float = 0

  public var offensiveMaximumScore: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "POGOProtos.Settings.Master"

extension POGOProtos_Settings_Master_CombatNpcPersonality: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CombatNpcPersonality"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "personality_name"),
    2: .standard(proto: "super_effective_chance"),
    3: .standard(proto: "special_chance"),
    4: .standard(proto: "defensive_minimum_score"),
    5: .standard(proto: "defensive_maximum_score"),
    6: .standard(proto: "offensive_minimum_score"),
    7: .standard(proto: "offensive_maximum_score"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.personalityName)
      case 2: try decoder.decodeSingularFloatField(value: &self.superEffectiveChance)
      case 3: try decoder.decodeSingularFloatField(value: &self.specialChance)
      case 4: try decoder.decodeSingularFloatField(value: &self.defensiveMinimumScore)
      case 5: try decoder.decodeSingularFloatField(value: &self.defensiveMaximumScore)
      case 6: try decoder.decodeSingularFloatField(value: &self.offensiveMinimumScore)
      case 7: try decoder.decodeSingularFloatField(value: &self.offensiveMaximumScore)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.personalityName.isEmpty {
      try visitor.visitSingularStringField(value: self.personalityName, fieldNumber: 1)
    }
    if self.superEffectiveChance != 0 {
      try visitor.visitSingularFloatField(value: self.superEffectiveChance, fieldNumber: 2)
    }
    if self.specialChance != 0 {
      try visitor.visitSingularFloatField(value: self.specialChance, fieldNumber: 3)
    }
    if self.defensiveMinimumScore != 0 {
      try visitor.visitSingularFloatField(value: self.defensiveMinimumScore, fieldNumber: 4)
    }
    if self.defensiveMaximumScore != 0 {
      try visitor.visitSingularFloatField(value: self.defensiveMaximumScore, fieldNumber: 5)
    }
    if self.offensiveMinimumScore != 0 {
      try visitor.visitSingularFloatField(value: self.offensiveMinimumScore, fieldNumber: 6)
    }
    if self.offensiveMaximumScore != 0 {
      try visitor.visitSingularFloatField(value: self.offensiveMaximumScore, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: POGOProtos_Settings_Master_CombatNpcPersonality, rhs: POGOProtos_Settings_Master_CombatNpcPersonality) -> Bool {
    if lhs.personalityName != rhs.personalityName {return false}
    if lhs.superEffectiveChance != rhs.superEffectiveChance {return false}
    if lhs.specialChance != rhs.specialChance {return false}
    if lhs.defensiveMinimumScore != rhs.defensiveMinimumScore {return false}
    if lhs.defensiveMaximumScore != rhs.defensiveMaximumScore {return false}
    if lhs.offensiveMinimumScore != rhs.offensiveMinimumScore {return false}
    if lhs.offensiveMaximumScore != rhs.offensiveMaximumScore {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
