// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Settings/Master/Item/VsSeekerAttributes.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct POGOProtos_Settings_Master_Item_VsSeekerAttributes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var vsSeekerStatus: POGOProtos_Settings_Master_Item_VsSeekerAttributes.VsSeekerStatus = .unset

  public var startKmWalked: Double = 0

  public var targetKmWalked: Double = 0

  public var battleGrantedRemaining: Int32 = 0

  public var vsSeekerUpgrades: [POGOProtos_Settings_Master_Item_VsSeekerAttributes.VsSeekerUpgrade] = []

  public var maxBattlesInSet: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum VsSeekerStatus: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case unset // = 0
    case startedCharging // = 1
    case fullyCharged // = 2
    case UNRECOGNIZED(Int)

    public init() {
      self = .unset
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unset
      case 1: self = .startedCharging
      case 2: self = .fullyCharged
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unset: return 0
      case .startedCharging: return 1
      case .fullyCharged: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  public struct VsSeekerUpgrade {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var itemID: String = String()

    public var distanceMultiplier: Float = 0

    public var numberOfBonusBattles: Int32 = 0

    public var inUse: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public init() {}
}

#if swift(>=4.2)

extension POGOProtos_Settings_Master_Item_VsSeekerAttributes.VsSeekerStatus: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [POGOProtos_Settings_Master_Item_VsSeekerAttributes.VsSeekerStatus] = [
    .unset,
    .startedCharging,
    .fullyCharged,
  ]
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "POGOProtos.Settings.Master.Item"

extension POGOProtos_Settings_Master_Item_VsSeekerAttributes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VsSeekerAttributes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "vs_seeker_status"),
    2: .standard(proto: "start_km_walked"),
    3: .standard(proto: "target_km_walked"),
    4: .standard(proto: "battle_granted_remaining"),
    5: .standard(proto: "vs_seeker_upgrades"),
    6: .standard(proto: "max_battles_in_set"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularEnumField(value: &self.vsSeekerStatus)
      case 2: try decoder.decodeSingularDoubleField(value: &self.startKmWalked)
      case 3: try decoder.decodeSingularDoubleField(value: &self.targetKmWalked)
      case 4: try decoder.decodeSingularInt32Field(value: &self.battleGrantedRemaining)
      case 5: try decoder.decodeRepeatedMessageField(value: &self.vsSeekerUpgrades)
      case 6: try decoder.decodeSingularInt32Field(value: &self.maxBattlesInSet)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.vsSeekerStatus != .unset {
      try visitor.visitSingularEnumField(value: self.vsSeekerStatus, fieldNumber: 1)
    }
    if self.startKmWalked != 0 {
      try visitor.visitSingularDoubleField(value: self.startKmWalked, fieldNumber: 2)
    }
    if self.targetKmWalked != 0 {
      try visitor.visitSingularDoubleField(value: self.targetKmWalked, fieldNumber: 3)
    }
    if self.battleGrantedRemaining != 0 {
      try visitor.visitSingularInt32Field(value: self.battleGrantedRemaining, fieldNumber: 4)
    }
    if !self.vsSeekerUpgrades.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.vsSeekerUpgrades, fieldNumber: 5)
    }
    if self.maxBattlesInSet != 0 {
      try visitor.visitSingularInt32Field(value: self.maxBattlesInSet, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: POGOProtos_Settings_Master_Item_VsSeekerAttributes, rhs: POGOProtos_Settings_Master_Item_VsSeekerAttributes) -> Bool {
    if lhs.vsSeekerStatus != rhs.vsSeekerStatus {return false}
    if lhs.startKmWalked != rhs.startKmWalked {return false}
    if lhs.targetKmWalked != rhs.targetKmWalked {return false}
    if lhs.battleGrantedRemaining != rhs.battleGrantedRemaining {return false}
    if lhs.vsSeekerUpgrades != rhs.vsSeekerUpgrades {return false}
    if lhs.maxBattlesInSet != rhs.maxBattlesInSet {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension POGOProtos_Settings_Master_Item_VsSeekerAttributes.VsSeekerStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNSET"),
    1: .same(proto: "STARTED_CHARGING"),
    2: .same(proto: "FULLY_CHARGED"),
  ]
}

extension POGOProtos_Settings_Master_Item_VsSeekerAttributes.VsSeekerUpgrade: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = POGOProtos_Settings_Master_Item_VsSeekerAttributes.protoMessageName + ".VsSeekerUpgrade"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "item_id"),
    2: .standard(proto: "distance_multiplier"),
    3: .standard(proto: "number_of_bonus_battles"),
    4: .standard(proto: "in_use"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.itemID)
      case 2: try decoder.decodeSingularFloatField(value: &self.distanceMultiplier)
      case 3: try decoder.decodeSingularInt32Field(value: &self.numberOfBonusBattles)
      case 4: try decoder.decodeSingularBoolField(value: &self.inUse)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.itemID.isEmpty {
      try visitor.visitSingularStringField(value: self.itemID, fieldNumber: 1)
    }
    if self.distanceMultiplier != 0 {
      try visitor.visitSingularFloatField(value: self.distanceMultiplier, fieldNumber: 2)
    }
    if self.numberOfBonusBattles != 0 {
      try visitor.visitSingularInt32Field(value: self.numberOfBonusBattles, fieldNumber: 3)
    }
    if self.inUse != false {
      try visitor.visitSingularBoolField(value: self.inUse, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: POGOProtos_Settings_Master_Item_VsSeekerAttributes.VsSeekerUpgrade, rhs: POGOProtos_Settings_Master_Item_VsSeekerAttributes.VsSeekerUpgrade) -> Bool {
    if lhs.itemID != rhs.itemID {return false}
    if lhs.distanceMultiplier != rhs.distanceMultiplier {return false}
    if lhs.numberOfBonusBattles != rhs.numberOfBonusBattles {return false}
    if lhs.inUse != rhs.inUse {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
