// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Map/Pokemon/MapPokemon.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct POGOProtos_Map_Pokemon_MapPokemon {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var spawnPointID: String = String()

  public var encounterID: UInt64 = 0

  public var pokedexTypeID: POGOProtos_Enums_PokemonId = .missingno

  public var expirationTimeMs: Int64 = 0

  public var latitude: Double = 0

  public var longitude: Double = 0

  public var pokemonDisplay: POGOProtos_Data_PokemonDisplay {
    get {return _pokemonDisplay ?? POGOProtos_Data_PokemonDisplay()}
    set {_pokemonDisplay = newValue}
  }
  /// Returns true if `pokemonDisplay` has been explicitly set.
  public var hasPokemonDisplay: Bool {return self._pokemonDisplay != nil}
  /// Clears the value of `pokemonDisplay`. Subsequent reads from it will return its default value.
  public mutating func clearPokemonDisplay() {self._pokemonDisplay = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _pokemonDisplay: POGOProtos_Data_PokemonDisplay? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "POGOProtos.Map.Pokemon"

extension POGOProtos_Map_Pokemon_MapPokemon: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MapPokemon"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "spawn_point_id"),
    2: .standard(proto: "encounter_id"),
    3: .standard(proto: "pokedex_type_id"),
    4: .standard(proto: "expiration_time_ms"),
    5: .same(proto: "latitude"),
    6: .same(proto: "longitude"),
    7: .standard(proto: "pokemon_display"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.spawnPointID)
      case 2: try decoder.decodeSingularFixed64Field(value: &self.encounterID)
      case 3: try decoder.decodeSingularEnumField(value: &self.pokedexTypeID)
      case 4: try decoder.decodeSingularInt64Field(value: &self.expirationTimeMs)
      case 5: try decoder.decodeSingularDoubleField(value: &self.latitude)
      case 6: try decoder.decodeSingularDoubleField(value: &self.longitude)
      case 7: try decoder.decodeSingularMessageField(value: &self._pokemonDisplay)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.spawnPointID.isEmpty {
      try visitor.visitSingularStringField(value: self.spawnPointID, fieldNumber: 1)
    }
    if self.encounterID != 0 {
      try visitor.visitSingularFixed64Field(value: self.encounterID, fieldNumber: 2)
    }
    if self.pokedexTypeID != .missingno {
      try visitor.visitSingularEnumField(value: self.pokedexTypeID, fieldNumber: 3)
    }
    if self.expirationTimeMs != 0 {
      try visitor.visitSingularInt64Field(value: self.expirationTimeMs, fieldNumber: 4)
    }
    if self.latitude != 0 {
      try visitor.visitSingularDoubleField(value: self.latitude, fieldNumber: 5)
    }
    if self.longitude != 0 {
      try visitor.visitSingularDoubleField(value: self.longitude, fieldNumber: 6)
    }
    if let v = self._pokemonDisplay {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: POGOProtos_Map_Pokemon_MapPokemon, rhs: POGOProtos_Map_Pokemon_MapPokemon) -> Bool {
    if lhs.spawnPointID != rhs.spawnPointID {return false}
    if lhs.encounterID != rhs.encounterID {return false}
    if lhs.pokedexTypeID != rhs.pokedexTypeID {return false}
    if lhs.expirationTimeMs != rhs.expirationTimeMs {return false}
    if lhs.latitude != rhs.latitude {return false}
    if lhs.longitude != rhs.longitude {return false}
    if lhs._pokemonDisplay != rhs._pokemonDisplay {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
