// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Networking/Responses/CheckPhotobombResponse.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct POGOProtos_Networking_Responses_CheckPhotobombResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var status: POGOProtos_Networking_Responses_CheckPhotobombResponse.Status = .unset

  public var photobombPokemonID: POGOProtos_Enums_PokemonId = .missingno

  public var photobombPokemonDisplay: POGOProtos_Data_PokemonDisplay {
    get {return _photobombPokemonDisplay ?? POGOProtos_Data_PokemonDisplay()}
    set {_photobombPokemonDisplay = newValue}
  }
  /// Returns true if `photobombPokemonDisplay` has been explicitly set.
  public var hasPhotobombPokemonDisplay: Bool {return self._photobombPokemonDisplay != nil}
  /// Clears the value of `photobombPokemonDisplay`. Subsequent reads from it will return its default value.
  public mutating func clearPhotobombPokemonDisplay() {self._photobombPokemonDisplay = nil}

  public var encounterID: UInt64 = 0

  public var uri: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum Status: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case unset // = 0
    case success // = 1
    case errorPhotoPokemonInvalid // = 2
    case errorUnknown // = 3
    case UNRECOGNIZED(Int)

    public init() {
      self = .unset
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unset
      case 1: self = .success
      case 2: self = .errorPhotoPokemonInvalid
      case 3: self = .errorUnknown
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unset: return 0
      case .success: return 1
      case .errorPhotoPokemonInvalid: return 2
      case .errorUnknown: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  public init() {}

  fileprivate var _photobombPokemonDisplay: POGOProtos_Data_PokemonDisplay? = nil
}

#if swift(>=4.2)

extension POGOProtos_Networking_Responses_CheckPhotobombResponse.Status: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [POGOProtos_Networking_Responses_CheckPhotobombResponse.Status] = [
    .unset,
    .success,
    .errorPhotoPokemonInvalid,
    .errorUnknown,
  ]
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "POGOProtos.Networking.Responses"

extension POGOProtos_Networking_Responses_CheckPhotobombResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CheckPhotobombResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "status"),
    2: .standard(proto: "photobomb_pokemon_id"),
    3: .standard(proto: "photobomb_pokemon_display"),
    4: .standard(proto: "encounter_id"),
    5: .same(proto: "uri"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularEnumField(value: &self.status)
      case 2: try decoder.decodeSingularEnumField(value: &self.photobombPokemonID)
      case 3: try decoder.decodeSingularMessageField(value: &self._photobombPokemonDisplay)
      case 4: try decoder.decodeSingularFixed64Field(value: &self.encounterID)
      case 5: try decoder.decodeSingularStringField(value: &self.uri)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.status != .unset {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 1)
    }
    if self.photobombPokemonID != .missingno {
      try visitor.visitSingularEnumField(value: self.photobombPokemonID, fieldNumber: 2)
    }
    if let v = self._photobombPokemonDisplay {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }
    if self.encounterID != 0 {
      try visitor.visitSingularFixed64Field(value: self.encounterID, fieldNumber: 4)
    }
    if !self.uri.isEmpty {
      try visitor.visitSingularStringField(value: self.uri, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: POGOProtos_Networking_Responses_CheckPhotobombResponse, rhs: POGOProtos_Networking_Responses_CheckPhotobombResponse) -> Bool {
    if lhs.status != rhs.status {return false}
    if lhs.photobombPokemonID != rhs.photobombPokemonID {return false}
    if lhs._photobombPokemonDisplay != rhs._photobombPokemonDisplay {return false}
    if lhs.encounterID != rhs.encounterID {return false}
    if lhs.uri != rhs.uri {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension POGOProtos_Networking_Responses_CheckPhotobombResponse.Status: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNSET"),
    1: .same(proto: "SUCCESS"),
    2: .same(proto: "ERROR_PHOTO_POKEMON_INVALID"),
    3: .same(proto: "ERROR_UNKNOWN"),
  ]
}
