// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Networking/Responses/BelugaTransactionCompleteResponse.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct POGOProtos_Networking_Responses_BelugaTransactionCompleteResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var status: POGOProtos_Networking_Responses_BelugaTransactionCompleteResponse.Status = .unset

  public var candyAwarded: Int32 = 0

  public var lootAwarded: POGOProtos_Inventory_Loot {
    get {return _lootAwarded ?? POGOProtos_Inventory_Loot()}
    set {_lootAwarded = newValue}
  }
  /// Returns true if `lootAwarded` has been explicitly set.
  public var hasLootAwarded: Bool {return self._lootAwarded != nil}
  /// Clears the value of `lootAwarded`. Subsequent reads from it will return its default value.
  public mutating func clearLootAwarded() {self._lootAwarded = nil}

  public var belugaFinalizeResponse: POGOProtos_Data_Beluga_BelugaBleFinalizeTransfer {
    get {return _belugaFinalizeResponse ?? POGOProtos_Data_Beluga_BelugaBleFinalizeTransfer()}
    set {_belugaFinalizeResponse = newValue}
  }
  /// Returns true if `belugaFinalizeResponse` has been explicitly set.
  public var hasBelugaFinalizeResponse: Bool {return self._belugaFinalizeResponse != nil}
  /// Clears the value of `belugaFinalizeResponse`. Subsequent reads from it will return its default value.
  public mutating func clearBelugaFinalizeResponse() {self._belugaFinalizeResponse = nil}

  public var bucketsUntilWeeklyAward: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum Status: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case unset // = 0
    case success // = 1
    case failed // = 2
    case errorInvalidPokemonID // = 3
    case errorPokemonDeployed // = 4
    case errorPokemonNotAllowed // = 5
    case errorPokemonIsBuddy // = 6
    case errorInvalidTransactionID // = 7
    case errorMissingTransactionID // = 8
    case UNRECOGNIZED(Int)

    public init() {
      self = .unset
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unset
      case 1: self = .success
      case 2: self = .failed
      case 3: self = .errorInvalidPokemonID
      case 4: self = .errorPokemonDeployed
      case 5: self = .errorPokemonNotAllowed
      case 6: self = .errorPokemonIsBuddy
      case 7: self = .errorInvalidTransactionID
      case 8: self = .errorMissingTransactionID
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unset: return 0
      case .success: return 1
      case .failed: return 2
      case .errorInvalidPokemonID: return 3
      case .errorPokemonDeployed: return 4
      case .errorPokemonNotAllowed: return 5
      case .errorPokemonIsBuddy: return 6
      case .errorInvalidTransactionID: return 7
      case .errorMissingTransactionID: return 8
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  public init() {}

  fileprivate var _lootAwarded: POGOProtos_Inventory_Loot? = nil
  fileprivate var _belugaFinalizeResponse: POGOProtos_Data_Beluga_BelugaBleFinalizeTransfer? = nil
}

#if swift(>=4.2)

extension POGOProtos_Networking_Responses_BelugaTransactionCompleteResponse.Status: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [POGOProtos_Networking_Responses_BelugaTransactionCompleteResponse.Status] = [
    .unset,
    .success,
    .failed,
    .errorInvalidPokemonID,
    .errorPokemonDeployed,
    .errorPokemonNotAllowed,
    .errorPokemonIsBuddy,
    .errorInvalidTransactionID,
    .errorMissingTransactionID,
  ]
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "POGOProtos.Networking.Responses"

extension POGOProtos_Networking_Responses_BelugaTransactionCompleteResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BelugaTransactionCompleteResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "status"),
    2: .standard(proto: "candy_awarded"),
    3: .standard(proto: "loot_awarded"),
    4: .standard(proto: "beluga_finalize_response"),
    5: .standard(proto: "buckets_until_weekly_award"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularEnumField(value: &self.status)
      case 2: try decoder.decodeSingularInt32Field(value: &self.candyAwarded)
      case 3: try decoder.decodeSingularMessageField(value: &self._lootAwarded)
      case 4: try decoder.decodeSingularMessageField(value: &self._belugaFinalizeResponse)
      case 5: try decoder.decodeSingularInt32Field(value: &self.bucketsUntilWeeklyAward)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.status != .unset {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 1)
    }
    if self.candyAwarded != 0 {
      try visitor.visitSingularInt32Field(value: self.candyAwarded, fieldNumber: 2)
    }
    if let v = self._lootAwarded {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }
    if let v = self._belugaFinalizeResponse {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }
    if self.bucketsUntilWeeklyAward != 0 {
      try visitor.visitSingularInt32Field(value: self.bucketsUntilWeeklyAward, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: POGOProtos_Networking_Responses_BelugaTransactionCompleteResponse, rhs: POGOProtos_Networking_Responses_BelugaTransactionCompleteResponse) -> Bool {
    if lhs.status != rhs.status {return false}
    if lhs.candyAwarded != rhs.candyAwarded {return false}
    if lhs._lootAwarded != rhs._lootAwarded {return false}
    if lhs._belugaFinalizeResponse != rhs._belugaFinalizeResponse {return false}
    if lhs.bucketsUntilWeeklyAward != rhs.bucketsUntilWeeklyAward {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension POGOProtos_Networking_Responses_BelugaTransactionCompleteResponse.Status: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNSET"),
    1: .same(proto: "SUCCESS"),
    2: .same(proto: "FAILED"),
    3: .same(proto: "ERROR_INVALID_POKEMON_ID"),
    4: .same(proto: "ERROR_POKEMON_DEPLOYED"),
    5: .same(proto: "ERROR_POKEMON_NOT_ALLOWED"),
    6: .same(proto: "ERROR_POKEMON_IS_BUDDY"),
    7: .same(proto: "ERROR_INVALID_TRANSACTION_ID"),
    8: .same(proto: "ERROR_MISSING_TRANSACTION_ID"),
  ]
}
