// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Networking/Responses/GetPhotobombResponse.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct POGOProtos_Networking_Responses_GetPhotobombResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var status: POGOProtos_Networking_Responses_GetPhotobombResponse.Status {
    get {return _storage._status}
    set {_uniqueStorage()._status = newValue}
  }

  public var pokemonID: POGOProtos_Enums_PokemonId {
    get {return _storage._pokemonID}
    set {_uniqueStorage()._pokemonID = newValue}
  }

  public var lat: Double {
    get {return _storage._lat}
    set {_uniqueStorage()._lat = newValue}
  }

  public var lng: Double {
    get {return _storage._lng}
    set {_uniqueStorage()._lng = newValue}
  }

  public var encounterLocation: String {
    get {return _storage._encounterLocation}
    set {_uniqueStorage()._encounterLocation = newValue}
  }

  public var encounterID: UInt64 {
    get {return _storage._encounterID}
    set {_uniqueStorage()._encounterID = newValue}
  }

  public var disappearTimeMs: Int64 {
    get {return _storage._disappearTimeMs}
    set {_uniqueStorage()._disappearTimeMs = newValue}
  }

  public var pokemonDisplay: POGOProtos_Data_PokemonDisplay {
    get {return _storage._pokemonDisplay ?? POGOProtos_Data_PokemonDisplay()}
    set {_uniqueStorage()._pokemonDisplay = newValue}
  }
  /// Returns true if `pokemonDisplay` has been explicitly set.
  public var hasPokemonDisplay: Bool {return _storage._pokemonDisplay != nil}
  /// Clears the value of `pokemonDisplay`. Subsequent reads from it will return its default value.
  public mutating func clearPokemonDisplay() {_uniqueStorage()._pokemonDisplay = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum Status: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case unset // = 0
    case success // = 1
    case photobombNotAvailable // = 2
    case encounterAlreadyCompleted // = 3
    case errorUnknown // = 4
    case UNRECOGNIZED(Int)

    public init() {
      self = .unset
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unset
      case 1: self = .success
      case 2: self = .photobombNotAvailable
      case 3: self = .encounterAlreadyCompleted
      case 4: self = .errorUnknown
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unset: return 0
      case .success: return 1
      case .photobombNotAvailable: return 2
      case .encounterAlreadyCompleted: return 3
      case .errorUnknown: return 4
      case .UNRECOGNIZED(let i): return i; default: print("[ERROR] \(#file) is not up to date!"); return 0
      }
    }

  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

#if swift(>=4.2)

extension POGOProtos_Networking_Responses_GetPhotobombResponse.Status: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [POGOProtos_Networking_Responses_GetPhotobombResponse.Status] = [
    .unset,
    .success,
    .photobombNotAvailable,
    .encounterAlreadyCompleted,
    .errorUnknown,
  ]
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "POGOProtos.Networking.Responses"

extension POGOProtos_Networking_Responses_GetPhotobombResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetPhotobombResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "status"),
    2: .standard(proto: "pokemon_id"),
    3: .same(proto: "lat"),
    4: .same(proto: "lng"),
    5: .standard(proto: "encounter_location"),
    6: .standard(proto: "encounter_id"),
    7: .standard(proto: "disappear_time_ms"),
    8: .standard(proto: "pokemon_display"),
  ]

  fileprivate class _StorageClass {
    var _status: POGOProtos_Networking_Responses_GetPhotobombResponse.Status = .unset
    var _pokemonID: POGOProtos_Enums_PokemonId = .missingno
    var _lat: Double = 0
    var _lng: Double = 0
    var _encounterLocation: String = String()
    var _encounterID: UInt64 = 0
    var _disappearTimeMs: Int64 = 0
    var _pokemonDisplay: POGOProtos_Data_PokemonDisplay? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _status = source._status
      _pokemonID = source._pokemonID
      _lat = source._lat
      _lng = source._lng
      _encounterLocation = source._encounterLocation
      _encounterID = source._encounterID
      _disappearTimeMs = source._disappearTimeMs
      _pokemonDisplay = source._pokemonDisplay
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularEnumField(value: &_storage._status)
        case 2: try decoder.decodeSingularEnumField(value: &_storage._pokemonID)
        case 3: try decoder.decodeSingularDoubleField(value: &_storage._lat)
        case 4: try decoder.decodeSingularDoubleField(value: &_storage._lng)
        case 5: try decoder.decodeSingularStringField(value: &_storage._encounterLocation)
        case 6: try decoder.decodeSingularFixed64Field(value: &_storage._encounterID)
        case 7: try decoder.decodeSingularInt64Field(value: &_storage._disappearTimeMs)
        case 8: try decoder.decodeSingularMessageField(value: &_storage._pokemonDisplay)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._status != .unset {
        try visitor.visitSingularEnumField(value: _storage._status, fieldNumber: 1)
      }
      if _storage._pokemonID != .missingno {
        try visitor.visitSingularEnumField(value: _storage._pokemonID, fieldNumber: 2)
      }
      if _storage._lat != 0 {
        try visitor.visitSingularDoubleField(value: _storage._lat, fieldNumber: 3)
      }
      if _storage._lng != 0 {
        try visitor.visitSingularDoubleField(value: _storage._lng, fieldNumber: 4)
      }
      if !_storage._encounterLocation.isEmpty {
        try visitor.visitSingularStringField(value: _storage._encounterLocation, fieldNumber: 5)
      }
      if _storage._encounterID != 0 {
        try visitor.visitSingularFixed64Field(value: _storage._encounterID, fieldNumber: 6)
      }
      if _storage._disappearTimeMs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._disappearTimeMs, fieldNumber: 7)
      }
      if let v = _storage._pokemonDisplay {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: POGOProtos_Networking_Responses_GetPhotobombResponse, rhs: POGOProtos_Networking_Responses_GetPhotobombResponse) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._status != rhs_storage._status {return false}
        if _storage._pokemonID != rhs_storage._pokemonID {return false}
        if _storage._lat != rhs_storage._lat {return false}
        if _storage._lng != rhs_storage._lng {return false}
        if _storage._encounterLocation != rhs_storage._encounterLocation {return false}
        if _storage._encounterID != rhs_storage._encounterID {return false}
        if _storage._disappearTimeMs != rhs_storage._disappearTimeMs {return false}
        if _storage._pokemonDisplay != rhs_storage._pokemonDisplay {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension POGOProtos_Networking_Responses_GetPhotobombResponse.Status: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNSET"),
    1: .same(proto: "SUCCESS"),
    2: .same(proto: "PHOTOBOMB_NOT_AVAILABLE"),
    3: .same(proto: "ENCOUNTER_ALREADY_COMPLETED"),
    4: .same(proto: "ERROR_UNKNOWN"),
  ]
}
