// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Networking/Responses/SetAvatarResponse.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct POGOProtos_Networking_Responses_SetAvatarResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var status: POGOProtos_Networking_Responses_SetAvatarResponse.Status = .unset

  public var playerData: POGOProtos_Data_PlayerData {
    get {return _playerData ?? POGOProtos_Data_PlayerData()}
    set {_playerData = newValue}
  }
  /// Returns true if `playerData` has been explicitly set.
  public var hasPlayerData: Bool {return self._playerData != nil}
  /// Clears the value of `playerData`. Subsequent reads from it will return its default value.
  public mutating func clearPlayerData() {self._playerData = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum Status: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case unset // = 0
    case success // = 1
    case avatarAlreadySet // = 2
    case failure // = 3
    case slotNotAllowed // = 4
    case itemNotOwned // = 5
    case invalidAvatarType // = 6
    case UNRECOGNIZED(Int)

    public init() {
      self = .unset
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unset
      case 1: self = .success
      case 2: self = .avatarAlreadySet
      case 3: self = .failure
      case 4: self = .slotNotAllowed
      case 5: self = .itemNotOwned
      case 6: self = .invalidAvatarType
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unset: return 0
      case .success: return 1
      case .avatarAlreadySet: return 2
      case .failure: return 3
      case .slotNotAllowed: return 4
      case .itemNotOwned: return 5
      case .invalidAvatarType: return 6
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  public init() {}

  fileprivate var _playerData: POGOProtos_Data_PlayerData? = nil
}

#if swift(>=4.2)

extension POGOProtos_Networking_Responses_SetAvatarResponse.Status: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [POGOProtos_Networking_Responses_SetAvatarResponse.Status] = [
    .unset,
    .success,
    .avatarAlreadySet,
    .failure,
    .slotNotAllowed,
    .itemNotOwned,
    .invalidAvatarType,
  ]
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "POGOProtos.Networking.Responses"

extension POGOProtos_Networking_Responses_SetAvatarResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SetAvatarResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "status"),
    2: .standard(proto: "player_data"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularEnumField(value: &self.status)
      case 2: try decoder.decodeSingularMessageField(value: &self._playerData)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.status != .unset {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 1)
    }
    if let v = self._playerData {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: POGOProtos_Networking_Responses_SetAvatarResponse, rhs: POGOProtos_Networking_Responses_SetAvatarResponse) -> Bool {
    if lhs.status != rhs.status {return false}
    if lhs._playerData != rhs._playerData {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension POGOProtos_Networking_Responses_SetAvatarResponse.Status: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNSET"),
    1: .same(proto: "SUCCESS"),
    2: .same(proto: "AVATAR_ALREADY_SET"),
    3: .same(proto: "FAILURE"),
    4: .same(proto: "SLOT_NOT_ALLOWED"),
    5: .same(proto: "ITEM_NOT_OWNED"),
    6: .same(proto: "INVALID_AVATAR_TYPE"),
  ]
}
