// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Enums/PluginState.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum POGOProtos_Enums_PluginState: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case unknownPluginState // = 0
  case initialized // = 1
  case starting // = 2
  case started // = 3
  case resumed // = 4
  case paused // = 5
  case stopped // = 6
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknownPluginState
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknownPluginState
    case 1: self = .initialized
    case 2: self = .starting
    case 3: self = .started
    case 4: self = .resumed
    case 5: self = .paused
    case 6: self = .stopped
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknownPluginState: return 0
    case .initialized: return 1
    case .starting: return 2
    case .started: return 3
    case .resumed: return 4
    case .paused: return 5
    case .stopped: return 6
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension POGOProtos_Enums_PluginState: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [POGOProtos_Enums_PluginState] = [
    .unknownPluginState,
    .initialized,
    .starting,
    .started,
    .resumed,
    .paused,
    .stopped,
  ]
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension POGOProtos_Enums_PluginState: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNKNOWN_PLUGIN_STATE"),
    1: .same(proto: "INITIALIZED"),
    2: .same(proto: "STARTING"),
    3: .same(proto: "STARTED"),
    4: .same(proto: "RESUMED"),
    5: .same(proto: "PAUSED"),
    6: .same(proto: "STOPPED"),
  ]
}
