// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Networking/Requests/Game/GamePoi/Requests/SubmitSponsorPoiReportMessage.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct POGOProtos_Networking_Requests_Game_GamePoi_Requests_SubmitSponsorPoiReportMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var poiID: String = String()

  public var invalidReason: POGOProtos_Networking_Requests_Game_GamePoi_Requests_SubmitSponsorPoiReportMessage.SponsorPoiInvalidReason = .sponsorPoiReasonUnspecified

  public var additionalDetails: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum SponsorPoiInvalidReason: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case sponsorPoiReasonUnspecified // = 0
    case sponsorPoiReasonDoesNotExist // = 1
    case sponsorPoiReasonNotSafe // = 2
    case sponsorPoiReasonNotTruthful // = 3
    case sponsorPoiReasonNotFamilyFriendly // = 4
    case sponsorPoiReasonOffensiveContent // = 5
    case UNRECOGNIZED(Int)

    public init() {
      self = .sponsorPoiReasonUnspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .sponsorPoiReasonUnspecified
      case 1: self = .sponsorPoiReasonDoesNotExist
      case 2: self = .sponsorPoiReasonNotSafe
      case 3: self = .sponsorPoiReasonNotTruthful
      case 4: self = .sponsorPoiReasonNotFamilyFriendly
      case 5: self = .sponsorPoiReasonOffensiveContent
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .sponsorPoiReasonUnspecified: return 0
      case .sponsorPoiReasonDoesNotExist: return 1
      case .sponsorPoiReasonNotSafe: return 2
      case .sponsorPoiReasonNotTruthful: return 3
      case .sponsorPoiReasonNotFamilyFriendly: return 4
      case .sponsorPoiReasonOffensiveContent: return 5
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  public init() {}
}

#if swift(>=4.2)

extension POGOProtos_Networking_Requests_Game_GamePoi_Requests_SubmitSponsorPoiReportMessage.SponsorPoiInvalidReason: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [POGOProtos_Networking_Requests_Game_GamePoi_Requests_SubmitSponsorPoiReportMessage.SponsorPoiInvalidReason] = [
    .sponsorPoiReasonUnspecified,
    .sponsorPoiReasonDoesNotExist,
    .sponsorPoiReasonNotSafe,
    .sponsorPoiReasonNotTruthful,
    .sponsorPoiReasonNotFamilyFriendly,
    .sponsorPoiReasonOffensiveContent,
  ]
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "POGOProtos.Networking.Requests.Game.GamePoi.Requests"

extension POGOProtos_Networking_Requests_Game_GamePoi_Requests_SubmitSponsorPoiReportMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SubmitSponsorPoiReportMessage"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "poi_id"),
    2: .standard(proto: "invalid_reason"),
    3: .standard(proto: "additional_details"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.poiID)
      case 2: try decoder.decodeSingularEnumField(value: &self.invalidReason)
      case 3: try decoder.decodeSingularStringField(value: &self.additionalDetails)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.poiID.isEmpty {
      try visitor.visitSingularStringField(value: self.poiID, fieldNumber: 1)
    }
    if self.invalidReason != .sponsorPoiReasonUnspecified {
      try visitor.visitSingularEnumField(value: self.invalidReason, fieldNumber: 2)
    }
    if !self.additionalDetails.isEmpty {
      try visitor.visitSingularStringField(value: self.additionalDetails, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: POGOProtos_Networking_Requests_Game_GamePoi_Requests_SubmitSponsorPoiReportMessage, rhs: POGOProtos_Networking_Requests_Game_GamePoi_Requests_SubmitSponsorPoiReportMessage) -> Bool {
    if lhs.poiID != rhs.poiID {return false}
    if lhs.invalidReason != rhs.invalidReason {return false}
    if lhs.additionalDetails != rhs.additionalDetails {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension POGOProtos_Networking_Requests_Game_GamePoi_Requests_SubmitSponsorPoiReportMessage.SponsorPoiInvalidReason: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "SPONSOR_POI_REASON_UNSPECIFIED"),
    1: .same(proto: "SPONSOR_POI_REASON_DOES_NOT_EXIST"),
    2: .same(proto: "SPONSOR_POI_REASON_NOT_SAFE"),
    3: .same(proto: "SPONSOR_POI_REASON_NOT_TRUTHFUL"),
    4: .same(proto: "SPONSOR_POI_REASON_NOT_FAMILY_FRIENDLY"),
    5: .same(proto: "SPONSOR_POI_REASON_OFFENSIVE_CONTENT"),
  ]
}
