// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Networking/Requests/Messages/ListAvatarCustomizationsMessage.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct POGOProtos_Networking_Requests_Messages_ListAvatarCustomizationsMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var avatarType: POGOProtos_Data_Player_PlayerAvatarType = .playerAvatarMale

  public var slot: [POGOProtos_Data_Avatar_AvatarCustomization.Slot] = []

  public var filters: [POGOProtos_Enums_Filter] = []

  public var start: Int32 = 0

  public var limit: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "POGOProtos.Networking.Requests.Messages"

extension POGOProtos_Networking_Requests_Messages_ListAvatarCustomizationsMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListAvatarCustomizationsMessage"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "avatar_type"),
    2: .same(proto: "slot"),
    3: .same(proto: "filters"),
    4: .same(proto: "start"),
    5: .same(proto: "limit"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularEnumField(value: &self.avatarType)
      case 2: try decoder.decodeRepeatedEnumField(value: &self.slot)
      case 3: try decoder.decodeRepeatedEnumField(value: &self.filters)
      case 4: try decoder.decodeSingularInt32Field(value: &self.start)
      case 5: try decoder.decodeSingularInt32Field(value: &self.limit)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.avatarType != .playerAvatarMale {
      try visitor.visitSingularEnumField(value: self.avatarType, fieldNumber: 1)
    }
    if !self.slot.isEmpty {
      try visitor.visitPackedEnumField(value: self.slot, fieldNumber: 2)
    }
    if !self.filters.isEmpty {
      try visitor.visitPackedEnumField(value: self.filters, fieldNumber: 3)
    }
    if self.start != 0 {
      try visitor.visitSingularInt32Field(value: self.start, fieldNumber: 4)
    }
    if self.limit != 0 {
      try visitor.visitSingularInt32Field(value: self.limit, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: POGOProtos_Networking_Requests_Messages_ListAvatarCustomizationsMessage, rhs: POGOProtos_Networking_Requests_Messages_ListAvatarCustomizationsMessage) -> Bool {
    if lhs.avatarType != rhs.avatarType {return false}
    if lhs.slot != rhs.slot {return false}
    if lhs.filters != rhs.filters {return false}
    if lhs.start != rhs.start {return false}
    if lhs.limit != rhs.limit {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
