// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Networking/Requests/Messages/GymBattleAttackMessage.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct POGOProtos_Networking_Requests_Messages_GymBattleAttackMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var gymID: String = String()

  public var battleID: String = String()

  public var attackerActions: [POGOProtos_Data_Battle_BattleAction] = []

  public var lastRetrievedAction: POGOProtos_Data_Battle_BattleAction {
    get {return _lastRetrievedAction ?? POGOProtos_Data_Battle_BattleAction()}
    set {_lastRetrievedAction = newValue}
  }
  /// Returns true if `lastRetrievedAction` has been explicitly set.
  public var hasLastRetrievedAction: Bool {return self._lastRetrievedAction != nil}
  /// Clears the value of `lastRetrievedAction`. Subsequent reads from it will return its default value.
  public mutating func clearLastRetrievedAction() {self._lastRetrievedAction = nil}

  public var playerLatDegrees: Double = 0

  public var playerLngDegrees: Double = 0

  public var timestampMs: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _lastRetrievedAction: POGOProtos_Data_Battle_BattleAction? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "POGOProtos.Networking.Requests.Messages"

extension POGOProtos_Networking_Requests_Messages_GymBattleAttackMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GymBattleAttackMessage"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "gym_id"),
    2: .standard(proto: "battle_id"),
    3: .standard(proto: "attacker_actions"),
    4: .standard(proto: "last_retrieved_action"),
    5: .standard(proto: "player_lat_degrees"),
    6: .standard(proto: "player_lng_degrees"),
    7: .standard(proto: "timestamp_ms"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.gymID)
      case 2: try decoder.decodeSingularStringField(value: &self.battleID)
      case 3: try decoder.decodeRepeatedMessageField(value: &self.attackerActions)
      case 4: try decoder.decodeSingularMessageField(value: &self._lastRetrievedAction)
      case 5: try decoder.decodeSingularDoubleField(value: &self.playerLatDegrees)
      case 6: try decoder.decodeSingularDoubleField(value: &self.playerLngDegrees)
      case 7: try decoder.decodeSingularInt64Field(value: &self.timestampMs)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.gymID.isEmpty {
      try visitor.visitSingularStringField(value: self.gymID, fieldNumber: 1)
    }
    if !self.battleID.isEmpty {
      try visitor.visitSingularStringField(value: self.battleID, fieldNumber: 2)
    }
    if !self.attackerActions.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.attackerActions, fieldNumber: 3)
    }
    if let v = self._lastRetrievedAction {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }
    if self.playerLatDegrees != 0 {
      try visitor.visitSingularDoubleField(value: self.playerLatDegrees, fieldNumber: 5)
    }
    if self.playerLngDegrees != 0 {
      try visitor.visitSingularDoubleField(value: self.playerLngDegrees, fieldNumber: 6)
    }
    if self.timestampMs != 0 {
      try visitor.visitSingularInt64Field(value: self.timestampMs, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: POGOProtos_Networking_Requests_Messages_GymBattleAttackMessage, rhs: POGOProtos_Networking_Requests_Messages_GymBattleAttackMessage) -> Bool {
    if lhs.gymID != rhs.gymID {return false}
    if lhs.battleID != rhs.battleID {return false}
    if lhs.attackerActions != rhs.attackerActions {return false}
    if lhs._lastRetrievedAction != rhs._lastRetrievedAction {return false}
    if lhs.playerLatDegrees != rhs.playerLatDegrees {return false}
    if lhs.playerLngDegrees != rhs.playerLngDegrees {return false}
    if lhs.timestampMs != rhs.timestampMs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
