// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Data/Beluga/BelugaBleTransfer.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct POGOProtos_Data_Beluga_BelugaBleTransferProto {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var serverResponse: POGOProtos_Data_Beluga_BelugaBleTransferPrep {
    get {return _storage._serverResponse ?? POGOProtos_Data_Beluga_BelugaBleTransferPrep()}
    set {_uniqueStorage()._serverResponse = newValue}
  }
  /// Returns true if `serverResponse` has been explicitly set.
  public var hasServerResponse: Bool {return _storage._serverResponse != nil}
  /// Clears the value of `serverResponse`. Subsequent reads from it will return its default value.
  public mutating func clearServerResponse() {_uniqueStorage()._serverResponse = nil}

  public var serverSignature: Data {
    get {return _storage._serverSignature}
    set {_uniqueStorage()._serverSignature = newValue}
  }

  public var localizedOrigins: [String] {
    get {return _storage._localizedOrigins}
    set {_uniqueStorage()._localizedOrigins = newValue}
  }

  public var language: String {
    get {return _storage._language}
    set {_uniqueStorage()._language = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "POGOProtos.Data.Beluga"

extension POGOProtos_Data_Beluga_BelugaBleTransferProto: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BelugaBleTransferProto"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "server_response"),
    2: .standard(proto: "server_signature"),
    3: .standard(proto: "localized_origins"),
    4: .same(proto: "language"),
  ]

  fileprivate class _StorageClass {
    var _serverResponse: POGOProtos_Data_Beluga_BelugaBleTransferPrep? = nil
    var _serverSignature: Data = SwiftProtobuf.Internal.emptyData
    var _localizedOrigins: [String] = []
    var _language: String = String()

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _serverResponse = source._serverResponse
      _serverSignature = source._serverSignature
      _localizedOrigins = source._localizedOrigins
      _language = source._language
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._serverResponse)
        case 2: try decoder.decodeSingularBytesField(value: &_storage._serverSignature)
        case 3: try decoder.decodeRepeatedStringField(value: &_storage._localizedOrigins)
        case 4: try decoder.decodeSingularStringField(value: &_storage._language)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._serverResponse {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if !_storage._serverSignature.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._serverSignature, fieldNumber: 2)
      }
      if !_storage._localizedOrigins.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._localizedOrigins, fieldNumber: 3)
      }
      if !_storage._language.isEmpty {
        try visitor.visitSingularStringField(value: _storage._language, fieldNumber: 4)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: POGOProtos_Data_Beluga_BelugaBleTransferProto, rhs: POGOProtos_Data_Beluga_BelugaBleTransferProto) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._serverResponse != rhs_storage._serverResponse {return false}
        if _storage._serverSignature != rhs_storage._serverSignature {return false}
        if _storage._localizedOrigins != rhs_storage._localizedOrigins {return false}
        if _storage._language != rhs_storage._language {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
