name: Swift

on:
  push:
    branches: [ master, update ]
  pull_request:
    branches: [ master, update ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
